### ISSUE TITLE
Docs generation is not working

### ISSUE THREAD

**Issue by gerbil** [hashicorp/terraform-provider-scaffolding-framework#176] opened 2023-09-29 06:45 UTC
```
$ go generate
rendering website for provider "terraform-provider-scaffolding-framework" (as "terraform-provider-scaffolding-framework"
)
exporting schema from Terraform
compiling provider "scaffolding-framework"
using Terraform CLI binary from PATH if available, otherwise downloading latest Terraform CLI binary
running terraform init
Error executing command: unable to generate website: exit status 1

Error: Incompatible provider version

Provider registry.terraform.io/hashicorp/scaffolding-framework v0.0.1 does
not have a package available for your current platform, windows_386.

Provider releases are separate from Terraform CLI releases, so not all
providers are available for all platforms. Other versions of this provider
may have different platforms supported.



exit status 1
main.go:23: running "go": exit status 1
```

**Comment by bflad** [comment] 2024-01-05 19:19
Hi @gerbil 👋 Thank you for raising this and sorry for the delayed response here.

This particular report appears to be a duplicate of https://github.com/hashicorp/terraform-plugin-docs/issues/286 so I'm going to close it as the terraform-plugin-docs issue tracker is better suited for discussing issues relating to that tooling. I do not believe anything needs to be changed in this template repository that cannot be better suited by changes in the documentation generation tooling itself. Please note that the developer-side solution noted there is to ensure that both `tfplugindocs` and `terraform` are using the same architecture binaries, so in your particular case either both `386` or both `x86_64`. 👍

**Closed by bflad** 2024-01-05 19:19 UTC
